Module3 task1
htmlacademy-react/407511-six-cities-5 pull request #5
Opened 2020-10-18 21:41 UTC by randomrationalizer

2020-10-19 07:19 UTC, aelyseev commented on public/css/main.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{-we
А нет ли тут ошибки? Это похоже что файл из build попал в git

2020-10-19 07:26 UTC, aelyseev commented on src/components/app/app.jsx
> +              <OfferDetails
можно так, а можно `OfferDetails` обернуть в `withRouter`

2020-10-19 08:27 UTC, aelyseev requested changes

2020-10-19 08:27 UTC, aelyseev commented on src/components/offer-details/offer-details.jsx
> +                  <img className="header__logo" src="/img/logo.svg" alt="6 cities logo" width="81" height="41" />
На проектах с webpack это обычно так
```
import logo from 'path/to/logo'
...
<img className="header__logo" src={logo}  />
```

2020-10-19 08:27 UTC, aelyseev commented on src/components/offer-details/offer-details.jsx
> +                      <li key={nanoid()} className="property__inside-item">{option}</li>
плохой key

2020-10-19 08:27 UTC, aelyseev commented on src/components/offer-details/offer-details.jsx
> +                      <p key={nanoid()} className="property__text">{`${sentence}.`}</p>
плохой key — напрасно вы так eslint обманываете.

2020-10-19 08:27 UTC, aelyseev commented on src/components/offer-details/offer-details.jsx
> +                      <p key={nanoid()} className="property__text">{`${sentence}.`}</p>
и везде где это не написано, это тоже ошибка.

2020-10-19 08:27 UTC, aelyseev commented on src/components/offer-details/offer-details.jsx
> +                      <li key={nanoid()} className="reviews__item">
key

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +  }
```
this._handleFormFieldChange = this._handleFormFieldChange.bind(this);
```
не ошибка, но тоже самое, просто удобнее и читаемее =>
```
_handleFormFieldChange = (name, value) => {
    this.setState({
      [name]: value
    });
};
```

Да и знак подчеркивания вначале для обозначения приватности в многих проектах считается ошибкой.

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +        action="#"
лишнее

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +            <React.Fragment key={nanoid()}>
key

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +            <React.Fragment key={nanoid()}>
```
<React.Fragment></React.Fragment>
```
=> 
```
<></>
```

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +                  evt.preventDefault();
вынести в метод

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +                  evt.preventDefault();
упростить чтобы обработчик был постоянным

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +            evt.preventDefault();
упростить чтобы обработчик был постоянным

2020-10-19 08:27 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +            evt.preventDefault();
вынести в метод

2020-10-19 08:27 UTC, aelyseev commented on src/const.js
> +export const CITIES = [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
свалка из констант разного назначения и доменов

2020-10-19 08:27 UTC, aelyseev commented on src/const.js
> +export const CITIES = [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
не ошибка

2020-10-19 08:27 UTC, aelyseev commented on src/util/mock.js
> +const DESCRIPTION_MOCK = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet varius magna, non porta ligula feugiat eget. Fusce tristique felis at fermentum pharetra. Aliquam id or
не ошибка
есть такой npm пакет faker

2020-10-19 08:27 UTC, aelyseev commented on src/util/offer.js
> +export const getRatingInPercent = (ratingValue) => {
похоже на утилиту для моков, я бы похожил к мокам

2020-10-19 08:27 UTC, aelyseev commented on src/util/offer.js
> +    date = new Date(date);
можно упростить, moment понимает все что понимает Date

`return moment(date).format('YYYY-MM-DD');`

2020-10-19 08:27 UTC, aelyseev commented on src/util/offer.js
> +    date = new Date(date);
а тесты вас уже учили писать?

2020-10-23 06:32 UTC, randomrationalizer commented on public/css/main.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{-we
в main.css не описана стилизация активного состояния кнопки "Добавить в закладки" на странице объекта недвижимости:

```
<button class="property__bookmark-button button" type="button">
    <svg class="property__bookmark-icon" width="31" height="33">
      <use xlink:href="#icon-bookmark"></use>
    </svg>
    <span class="visually-hidden">To bookmarks</span>
</button>
```


в исходнике main.css было:

```
.property__bookmark-button--active .place-card__bookmark-icon {
    stroke: #4481c3;
    fill: #4481c3
}
```


внесены исправления:

```
.property__bookmark-button--active .property__bookmark-icon {
    stroke: #4481c3;
    fill: #4481c3
}
```

2020-10-23 06:41 UTC, randomrationalizer commented on src/components/review-form/review-form.jsx
> +  }
имеете в виду - объявить метод в конструкторе класса?

2020-10-23 06:42 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +  }
нет формат записи — стрелочная функция, который не требует bind в констукторе

2020-10-23 06:43 UTC, randomrationalizer commented on src/components/review-form/review-form.jsx
> +            <React.Fragment key={nanoid()}>
Спасибо, не знала про сокращённую запись.
А как быть с key при сокращённой записи?

2020-10-23 06:44 UTC, aelyseev commented on public/css/main.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{-we
Вопрос не в этом, это минифицированный css файл, который читать и править сложно. В git у вас исходники, а файлы после компиляции в git не включают

2020-10-23 07:44 UTC, randomrationalizer commented on public/css/main.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{-we
Ок, понятно.

2020-10-23 07:48 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +            <React.Fragment key={nanoid()}>
наверное `< key=""></>`, но я не уверен, не приходилось еще писать key для фрагментов

2020-10-23 08:04 UTC, randomrationalizer commented on src/components/review-form/review-form.jsx
> +  }
eslint не пропускает такое написание в классе

2020-10-23 08:08 UTC, randomrationalizer commented on src/components/review-form/review-form.jsx
> +            <React.Fragment key={nanoid()}>
в документации пишут, что не поддерживает ключи: https://ru.reactjs.org/docs/fragments.html#short-syntax

2020-10-23 08:11 UTC, randomrationalizer commented on src/const.js
> +export const CITIES = [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
Как лучше было бы сделать - перенести константы в компоненты или выделить отдельные файлы по назначению?

2020-10-23 08:14 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +  }
значит тогда это требование академии — оставьте как есть

2020-10-23 12:41 UTC, randomrationalizer commented on src/util/offer.js
> +    date = new Date(date);
Тесты будут в 8 разделе.

2020-10-23 12:56 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +            <React.Fragment key={nanoid()}>
Спасибо, тоже буду знать.

2020-10-23 13:10 UTC, aelyseev commented on src/const.js
> +export const CITIES = [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
1. Во-первых, я бы избавился от одноразовых констант, например, `CURRENT_CITY` используется только раз, и тут же передается как свойство.
2. То же `MAX_RATING` и `RatingValueToTitle`
3. `CardType` используется только в офферах — может лучше `OfferType`. Потом у вас есть несколько папок с компонентами `offer-card`, `offer-details`, `offers-list`. Можно объеденить это все в модуль(папку) `offer`, тогда вынести проверки типа `const isFavoritesCard = cardType === CardType.FAVORITES ? true : false;` в методы, `isFavorite`...
4. `OFFER_TYPES` тоже используется один раз — можно использовать только в модуле.

И вот общий совет. Это может идти в разрез, что говорят на лекциях, но не делайте константы такого типа про запас. А если делаете, то группируйте по доменному назначению. 

P.S. Это все опционально, конечно

2020-10-24 12:48 UTC, randomrationalizer commented on src/components/offer-card/offer-card.jsx
> +    <article className={`${cardType}__${cardType === CardType.MAIN ? `place-` : ``}card place-card`}
пробел тут не пропущен:
className для main - `cities__place-card place-card`
для favorites - `favorites__card place-card`
для рекомендаций - `near-places__card place-card`

2020-10-24 12:58 UTC, randomrationalizer commented on src/util/mock.js
> +const DESCRIPTION_MOCK = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet varius magna, non porta ligula feugiat eget. Fusce tristique felis at fermentum pharetra. Aliquam id or
Спасибо за рекомендацию!

2020-10-24 13:56 UTC, randomrationalizer commented on src/components/offer-details/offer-details.jsx
> +                  <img className="header__logo" src="/img/logo.svg" alt="6 cities logo" width="81" height="41" />
не совсем поняла вопрос.

2020-10-24 14:35 UTC, randomrationalizer commented on src/const.js
> +export const CITIES = [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
Спасибо за рекомендацию! 
правильно ли я понимаю, что можно создать класс `offer`  и задать в нём статичные методы для проверок по типу `isFavoritesCard` ... ?

2020-10-24 16:51 UTC, randomrationalizer commented on src/components/offer-card/offer-card.jsx
> +      onMouseOver={(evt) => {
мне кажется, что работает так:
Если курсор уходит с `article` - ничего не происходит, активная карточка записана в стейт компонента `OffersList`.
Когда курсор переходит на другой `article`, обновляется стейт `OffersList` и он перерисовывается.

2020-10-24 16:52 UTC, randomrationalizer commented on src/components/offer-card/offer-card.jsx
> +        evt.preventDefault();
Это результат бездумного использования preventDefault.
Событие `mouseover` - cancelable, но не могу найти информацию о том, что же является поведением по умолчанию.
Может быть, Вам приходилось сталкиваться?

2020-10-24 17:13 UTC, randomrationalizer commented on src/components/app/app.jsx
> +              <OfferDetails
При использовании `WithRouter` можно как-то по другому реализовать перенаправление в случае ошибочного id?

2020-10-26 13:53 UTC, aelyseev commented on src/const.js
> +export const CITIES = [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
Да, например, так. Или просто сделать в папке `utils.js` в котором экспротировать функции

2020-10-26 13:54 UTC, aelyseev commented on src/components/offer-card/offer-card.jsx
> +    <article className={`${cardType}__${cardType === CardType.MAIN ? `place-` : ``}card place-card`}
хорошо, но читается плоховато

2020-10-26 13:55 UTC, aelyseev commented on src/components/offer-card/offer-card.jsx
> +      onMouseOver={(evt) => {
Я имел ввиду, нет ли там ховера, который нужно убрать при `MouseOut`?

+ `MouseEnter` не генерирует событие для детей

2020-10-26 13:58 UTC, aelyseev commented on src/components/offer-card/offer-card.jsx
> +        evt.preventDefault();
на mouseover по умолчанию будут тултипы на ссылках, например. Но не вижу зачем бы их блокировать в этом случае.

2020-10-26 14:04 UTC, aelyseev commented on src/components/app/app.jsx
> +              <OfferDetails
`withRouter` просто прокидывает параметры то что вы передаете в render в свойства компонента — это декоратор.

2020-10-28 06:54 UTC, randomrationalizer commented on src/components/offer-card/offer-card.jsx
> +      onMouseOver={(evt) => {
Спасибо, поняла.

2020-10-29 12:34 UTC, aelyseev commented on package.json
> +    "moment": "2.29.1",
я так думаю что это вам на лекциях посоветовали, но в реальной жизни лучше `dayjs` или `date-fns`

2020-10-29 14:41 UTC, aelyseev requested changes

2020-10-29 14:41 UTC, aelyseev commented on src/components/favorites/favorites.jsx
> +import logo from "../../../public/img/logo.svg";
Сейчас не ошибка. Решение править или нет — за вами.

1. Для обработки svg у вас стоит `file-loader` с параметрами по умолчанию. Это значит что исходный файл будет скопирован в вашу выходную директорию, в вашем случае это `public` с именем в зависимости от хэша его содержимого, примерно как-то так `fe71202393381ac7bff6796c2d32aff6.svg`, а путь к этом файл будет результатом импорта в переменную logo, `import logo from "../../../public/img/logo.svg";`

1. Далее в переменной public у вас игроруются только файлы `public/bundle.js, public/bundle.js.map`, и значит результат билда придется или чистить или комитить, так как сгенерированные file-loader изображения будут считаться новыми файлами.

1. Файл импортированный таким образом можно положить куда угодно, например рядом с компонентом.

1. Чтобы убрать такие файлы из индекса git,  я бы поменял настройки loader в webpack, вместо того что там сейчас (+ в .gitignore добавить public/assets)
```
{
    test: /\.(png|svg|jpg|gif)$/,
    loader: 'file-loader',
    options: {
        name: 'assets/[name]-[contenthash:4].[ext]'
    },
},
```

2020-10-29 14:41 UTC, aelyseev commented on src/components/offer/offer-card/offer-card.jsx
> +          <a href={`/offer/${id}`}>{title}</a>
`a` => `Link`

2020-10-29 14:41 UTC, aelyseev commented on src/components/offer/offer-card/offer-card.jsx
> +        <a href={`/offer/${id}`}>
`a` => `Link`

2020-10-29 14:41 UTC, aelyseev commented on src/components/offer/offer-details/offer-details.jsx
> +                  <div key={index} className="property__image-wrapper">
`index` => `photo.src`

2020-10-29 14:41 UTC, aelyseev commented on src/components/offer/offer-details/offer-details.jsx
> +                      <p key={index} className="property__text">{`${sentence}.`}</p>
`index` => `sentence`

2020-10-29 14:41 UTC, aelyseev commented on src/components/offer/offer-details/offer-details.jsx
> +                      <li key={`${review.author}-${index}`} className="reviews__item">
неплохо, но лучше
`${review.author}-${index}` => `${review.author}-${review.text}`

2020-10-29 14:41 UTC, aelyseev commented on src/components/offer/util.js
> +  let first = a.date;
не ошибка, но можно проще
`moment(a.date) - moment(b.date)`, если в a или b, строка которую можно привести к дате или просто дата — moment все сделает за вас.
Так как у нас тут вычитание, то правая и левая части будут приведены к числам.

2020-10-29 14:41 UTC, aelyseev commented on src/components/review-form/review-form.jsx
> +const DEFAULT_STATE = {
не ошибка но, как правило в каком регистре, SCREAMING_SNAKE_CASE пишут строковые константы или числа.

Такие переменные как тут я бы писал в обычном формате

2020-10-29 14:41 UTC, aelyseev commented on webpack.config.js
> +                'file-loader',
написал выше рекомендации

2020-11-09 11:09 UTC, randomrationalizer commented on package.json
> +    "moment": "2.29.1",
Спасибо за рекомендацию, использовала dayjs.

2020-11-09 11:10 UTC, randomrationalizer commented on src/components/favorites/favorites.jsx
> +import logo from "../../../public/img/logo.svg";
Спасибо, исправила.

2020-11-13 09:36 UTC, aelyseev approved these changes

2020-11-13 09:37 UTC, merged